#pragma checksum "..\..\..\Model\LekarView.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "5AF230E8DF7E46923ABAE0DD349CC4A5A37A03BC19DC61137C2A376D97958C58"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bolnica.Model;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Bolnica.Model {
    
    
    /// <summary>
    /// LekarView
    /// </summary>
    public partial class LekarView : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 10 "..\..\..\Model\LekarView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Pretrazi;
        
        #line default
        #line hidden
        
        
        #line 11 "..\..\..\Model\LekarView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Prikazi;
        
        #line default
        #line hidden
        
        
        #line 12 "..\..\..\Model\LekarView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Otkazi;
        
        #line default
        #line hidden
        
        
        #line 13 "..\..\..\Model\LekarView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Izmeni;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Bolnica;component/model/lekarview.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Model\LekarView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.Pretrazi = ((System.Windows.Controls.Button)(target));
            
            #line 10 "..\..\..\Model\LekarView.xaml"
            this.Pretrazi.Click += new System.Windows.RoutedEventHandler(this.onClick1);
            
            #line default
            #line hidden
            return;
            case 2:
            this.Prikazi = ((System.Windows.Controls.Button)(target));
            
            #line 11 "..\..\..\Model\LekarView.xaml"
            this.Prikazi.Click += new System.Windows.RoutedEventHandler(this.onClick2);
            
            #line default
            #line hidden
            return;
            case 3:
            this.Otkazi = ((System.Windows.Controls.Button)(target));
            
            #line 12 "..\..\..\Model\LekarView.xaml"
            this.Otkazi.Click += new System.Windows.RoutedEventHandler(this.onClick3);
            
            #line default
            #line hidden
            return;
            case 4:
            this.Izmeni = ((System.Windows.Controls.Button)(target));
            
            #line 13 "..\..\..\Model\LekarView.xaml"
            this.Izmeni.Click += new System.Windows.RoutedEventHandler(this.onClick4);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

